### ISSUE TITLE
Upload Item Properties into Master

### ISSUE THREAD

**Issue by ZacharyABuck** [p-lange/Clockworld#1]
CONDITIONS.md

**Comment by ZacharyABuck** [comment]
[Conditions](https://github.com/p-lange/Clockworld/blob/master/Rules/CONDITIONS.md)

**Comment by p-lange** [comment]
- [x] Random Garbage
- [x] Armor
- [x] Weapons
- [x] Ammunition
- [x] Toxins

**Comment by p-lange** [comment]
Done.
